config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shortener.urls', namespace='shortener'))
]

shortener/urls.py
from django.urls import path

from . import views

app_name = 'shortner'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create_short'),
    path('<str:uuid>', views.shortened_go, name='shortened_go'),
]

shortener/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class URL(models.Model):
    link = models.CharField(max_length=99999)
    uuid = models.CharField(max_length=10)

    def get_absolute_urls(self):
        return reverse('shortener:create', kwargs={'url': self.link})

shortener/views.py
from django.shortcuts import render, redirect, get_object_or_404
import uuid
from .models import URL

# Create your views here.
def index(request):
    return render(request, 'base.html')

def create(request):
    if request.method == 'POST':
        url = request.POST['url']

        if URL.objects.filter(link=url):
            uid = get_object_or_404(URL, link=url).uuid
            return render(request, 'create_short.html', context={'short_url': uid})

        uid = str(uuid.uuid4())[:5]

        url = URL.objects.create(
            link = url,
            uuid = uid
        )
        url.save()

        request.session['short_link'] = uid
        return render(request, 'create_short.html', context={'short_url': uid})

def shortened_go(request, uuid):
    url = get_object_or_404(URL, uuid=uuid)
    short_link = url.link
    
    return redirect(short_link)

templates/base.html
{% load static %}

<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <title>URL Shortener {% block title %}| Insert a link{% endblock %}</title>
    </head>
    <body>
        <div class="card main" style="width: 45rem; margin: auto auto;">
            <div class="card-body">
                <h3 class="card-title">Link to shorten</h3>
                <form method="post" action="{% url 'shortener:create_short' %}" autocomplete="off">
                    {% csrf_token %}
                    <input type="text" placeholder="URL" name="url" class="form-control"><br>
                    <input type="submit" value="Get Short Link" class="btn btn-primary">
                </form>
                </form>
            </div>
        </div>
        
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/create_short.html
{% extends 'base.html' %}

{% block title %}
    | Link Created
{% endblock %}

{% block content %}
    <div class="card" style="width: 45rem; margin: auto auto;">
        <div class="card-body">
            {% if short_url %}
            <h3 class="card-title">
                <a href="http://localhost:8000/{{ short_url }}" target="_blank">http://localhost:8000/{{ short_url }}</a>
            </h3>
            {% endif %}
        </div>
    </div>
{% endblock %}